### ISSUE TITLE
Crash with a few* other mods

### ISSUE THREAD

**Issue by moisties** [Gluton-Official/ExperiencedAnvils#1]
Hello, unfortunately this causes a ScreenManager crash with other mods like Immersive Petroleum and Immersive Engineering to name a few.
[crash-2021-03-27_12.47.06-fml.txt](https://github.com/Gluton-Official/ExperiencedAnvils/files/6216324/crash-2021-03-27_12.47.06-fml.txt)

**Comment by Gluton-Official** [comment]
That's not good, I will try to fix this asap. Thanks for letting me know!

**Comment by Gluton-Official** [comment]
Charm also removes the xp cost for anvils, so this mod isn't needed if you have Charm.
